format_version: 3
pipeline {
  environment {
    registry = '500722624043.dkr.ecr.ap-south-1.amazonaws.com/techolution'
    registryCredential = '***'
    dockerImage = 'Dockerfile'
  }
  agent any
  stages {
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build vanshikamahajan/redis:latest"
        }
      }
    }
    stage('Deploy image') {
        steps{
            script{
                docker.withRegistry("500722624043.dkr.ecr.ap-south-1.amazonaws.com/techolution" + "registryCredential:*****") {
                    dockerImage.push()
                }
            }
        }
    }
  }
}
