format_version: 3
pipelines:
  build_and_publish_image:
    group: sample
    lock_behavior: unlockWhenFinished
    display_order: 1
    environment_variables:
    materials:
      git:
        git: 
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - build_and_publish_image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          build_image:
            timeout: 0
            artifacts:
            - external:
                id: bulletin-board
                store_id: dockerhub
                configuration:
                  options:
                    Image: vanshikamahajan/redis
                    Tag: redis
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -t vanshikamahajan/redis:latest . -f Dockerfile
                command: /bin/bash
                run_if: passed