format_version: 3
pipeline {
  environment {
    registry = 'https://ap-south-1.console.aws.amazon.com/ecr/repositories/techolution/?region=ap-south-1'
    registryCredential = '***'
    dockerImage = 'Dockerfile'
  }
  agent any
  stages {
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build vanshikamahajan/redis:latest"
        }
      }
    }
    stage('Deploy image') {
        steps{
            script{
                docker.withRegistry("https://ap-south-1.console.aws.amazon.com/ecr/repositories/techolution/?region=ap-south-1" + "registryCredential:*****") {
                    dockerImage.push()
                }
            }
        }
    }
  }
}
